### ISSUE TITLE
player library?

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [emoon/HippoPlayer#106]
hi

Since you are doing a great job making plugins for all music formats, would it maybe be possible to separate the player ui/rust code completely from the sound library code and make a C or C++ library project that can be used by other players? (HippoLib or so).
That library would be unique and maybe become the number 1 library that 'can play it all'

So hippoplayer uses hippolib which is made of all the different existing audio libs, nicely adapted to compile and work on each platform. All code you already have for priority of libraries to play, ... should be inside hippolib too.

It would also benefit the project because you could better see where a bug must be fixed IMHO. 
And additionally I read in an issue some people don't like the QT dependency: it would be super easy to make a command line program or other minimalist UI by just calling the HippoLib :-)
Other developers can do it easily too.

What do you  think?

**Comment by emoon** [comment]
Yes. This is already planned and is actually already working to some extent.

The Rust code handles loading of playback plugins, deals with the playlist, etc. The Rust code is then compiled to a dll/shared object the Qt program loads and then talks with.

https://github.com/emoon/HippoPlayer/issues/58 for terminal ui

Whatever people want to use it outside of HippoPlayer or not I'm not sure. The reason I made the separation is like you wrote that some people wants to use a terminal ui which is totally possible now but the terminal version is yet to be coded.

It would also be possible to make a "fullscreen version" that only shows visualizers without the need of the Qt front-end.

I will close this issue as this working as already, but if I'm thinking of exposing it to other devs I will open a new one.
