### ISSUE TITLE
feature: add libmodplug

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [emoon/HippoPlayer#116]
libmodplug is not on your plugin list yet i think

https://github.com/Konstanty/libmodplug

**Comment by emoon** [comment]
I think libopenmpt is based on libmodplug and with enhancements on top of it so I'm not sure if it makes sense to add support for it.

**Comment by jessicajonesunitedkingdom** [comment]
It could sound different?

**Comment by emoon** [comment]
Yeah but the question really comes down to if it's worth spending time on adding many libraries that pretty much can play the same formats. It all takes time and add maintenance and the time can be spent on other features instead so I'm a bit unsure about it.

**Comment by jessicajonesunitedkingdom** [comment]
OK I understand, this is low priority :)

**Comment by emoon** [comment]
Closed as libopenmpt covers all the needs here.
