### ISSUE TITLE
feature: add FMOD

### ISSUE THREAD

**Issue by ghost** [emoon/HippoPlayer#117]
FMOD can play some tracker formats

https://www.fmod.com/core

**Comment by emoon** [comment]
I'm not sure it's worth support fmod which is primary (these days) targeting other thing than tracker formats.

**Comment by jessicajonesunitedkingdom** [comment]
I just thought for hearing differences between all the libraries.

I hear a lot of differences.  But you decide if you add it

Read here for example :)

https://hydrogenaud.io/index.php?topic=119449.0

**Comment by emoon** [comment]
Tracker formats in case of xm, mod, etc doesn't include (for most cases that I know of at least) any soundchip emulation. In the case of adplug that just deals with that then it totally makes sense. It's the same for SID (C64) and and other soundchip based emulation.

**Comment by emoon** [comment]
Don't think it makes a lot of sense to do this so will close it for now
