### ISSUE TITLE
Add support for Adplug

### ISSUE THREAD

**Issue by glennlunder** [emoon/HippoPlayer#12]
https://github.com/adplug/adplug

Gives us support for a bunch of older adlib-based pc formats.

**Comment by glennlunder** [comment]
It might be worth noting that several of these formats use the same file suffix (for example .sng), so a simple suffix-check to identify file format will only do for the formats with unique suffixes.

**Comment by emoon** [comment]
Yeah. I think we will need a bit stronger type checking going forward. There will also be cases when plugins will support the same format so we need a way to prioritize which plugin to use (for example UADE supports mod and so do libopenmpt and we want to pick libopenmpt in that case)

**Comment by glennlunder** [comment]
Agreed - opened issue #42 for this.
