### ISSUE TITLE
High CPU load (even when idle)

### ISSUE THREAD

**Issue by knochenhans** [emoon/HippoPlayer#130]
HippoPlayer creates a high CPU load for me (constantly maxing out on of my CPUs), even if no track is playing.

**Comment by emoon** [comment]
I see. Is this after playing a track or just once the program has been started?

**Comment by knochenhans** [comment]
This is also the case for me right after starting the program with fresh config files and empty playlist.

**Comment by emoon** [comment]
Ok thanks! I will investigate.

**Comment by knochenhans** [comment]
This seems to have resolved itself in current versions, by the way.

**Comment by emoon** [comment]
ah, odd. I looked at some profiling on windows but I couldn't find any high-cpu usage. Will close this one for now and we can re-open if it happens again.
