### ISSUE TITLE
Westwood ADL format can't be played (Adplug)

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [emoon/HippoPlayer#135]
The Westwood ADL format can't be played (supported by Adplug). It seems to load 200 subsongs but foobar2000 loads much less subsongs.

Attached an example file. This file can be played successfully by foobar2000's adplug plugin.

[dune ii - 00.zip](https://github.com/emoon/HippoPlayer/files/5022850/dune.ii.-.00.zip)

**Comment by emoon** [comment]
Thanks for the report. I will take a look.

**Comment by jessicajonesunitedkingdom** [comment]
found same bug in foobar2000
A solution is explained here: https://hydrogenaud.io/index.php?topic=119636.0

**Comment by emoon** [comment]
Seems like an issue inside adplug for sure. I will use the workaround implemented in foobar2000 when I fix this issue.
