### ISSUE TITLE
Plugins, Views and Data separation

### ISSUE THREAD

**Issue by emoon** [emoon/HippoPlayer#39]
This is a bit of "random" ramblings to figure out a design for this.

Right now several parts are being a bit glued together which is problematic extension wise.

There are no plugins for "views" which is something should be be fixed. This is to allow custom visualization plugins for example.

No view in HippoPlayer should be "special" unless there is a really good reason. For example right now the `PlaylistView` owns the PlaylistData. It would be nicer if the Playlist could be a global concept that plugins can both consume and mutate if wanted. In the general case consuming would be more common (to show the playlist in some different way for example) while the `regular` playlist view would be responsible for most of the common operations such as adding and removing files.

Another thing is output of audio playback is hard-coded to a single backend. This would be good to separate as well to make it easier to have plugins writing to other sources (such as to file or streaming to some service)

The main application should be responsible to handing out data / fetching data from the plugins but some of the data may only be consumed by the plugins themselves even if main application just sends them around.

So this brings us to have something like this

```
* Output plugins (audio hw, file, streaming, etc)
* View plugins (show stuff, has access to the UI, visualization)
* Decoder plugins (decode stuff to a format (right now f32) for nr of channels (2 right now)). Decoder plugins also need a way to show a config UI.
* File plugins (for packed data, the way I see this is there is a global VFS (virtual file system) where files can get "mounted" into (think *nix style) This should all be transparent to decoders
```
Some global concepts

```
Playlist
Audio frames
.. likely more stuff
```
Also some kind of message passing between the plugins. Not sure how this should work. I think starting explicit and not trying to be very general would be a good start.

**Comment by truck** [comment]
-- oh look this is the idea I just asked for elsewhere.  Big yes to this (:

JSON or BSON, possibly, for external data serialization?

**Comment by emoon** [comment]
Yeah I haven't figured out the format for this yes but yes, the idea is to have plugins being message passing based (msgpack,capnproto,bson,etc springs to mind) that being said I haven't actually made a full design for this yet. The good point here is like you suggest is that it would be possible to send these message externally as well. It would also be possible to have a output plugin that just sends to a websocket or whatever that one can connect to.

**Comment by emoon** [comment]
This has more or less been implemented now
