### ISSUE TITLE
Implement binary file format checking

### ISSUE THREAD

**Issue by glennlunder** [emoon/HippoPlayer#42]
As we implement more libraries and thus add support for more formats, file suffix will not be a sufficient method for accurately determining a filetype. A pretty standard way to implement this would be to read a section of the file, and look for "magic bytes" or values at certain offsets.

**Comment by sagamusix** [comment]
Note that libopenmpt already has a probing interface for exactly this purpose. File extensions are baaaad. :)

**Comment by emoon** [comment]
Yeah I have seen it :) The plan is to have to expose a function that all plugins needs to implement so the main application can ask "can you play this". I just haven't done that yet :)
