### ISSUE TITLE
Error running HippoPlayer (dev version)

### ISSUE THREAD

**Issue by knochenhans** [emoon/HippoPlayer#64]
Hi, I’m getting an error running the binary, compiled from the current dev version:

```t2-output/linux-gcc-debug-default [dev●] » ./hippo_player 
The current directory is /mnt/Daten/Downloads/HippoPlayer/t2-output/linux-gcc-debug-default
Found playback plugin with callback data 0x7fe8d40d5880
Found playback plugin with callback data 0x7fe8d4eea1a0
Unable to load dynamic lib, err Load(Custom { kind: Other, error: "./libvgm.so: undefined symbol: clock_gettime_temp" })
Found playback plugin with callback data 0x7fe8d40ad380
Found playback plugin with callback data 0x7fe8cb7a86e0
Found playback plugin with callback data 0x7fe8d4ec3060
Found playback plugin with callback data 0x7fe8cab1efc0
Unable to load dynamic lib, err Load(Custom { kind: Other, error: "./libuade_plugin.so: undefined symbol: strlcat" })
ASSERT failure in QList<T>::at: "index out of range", file /mnt/Daten/Downloads/Qt/5.14.1/gcc_64/include/QtCore/qlist.h, line 571
[1]    2158315 abort (core dumped)  ./hippo_player```

**Comment by emoon** [comment]
I will take a look at it

**Comment by emoon** [comment]
Can you try to grab latest code and see if it works now?

**Comment by ragouel** [comment]
Doesn't work, same error. 
<pre><code>Config error: Unable to open data/config/global.cfg: No such file or directory (os error 2)
ASSERT failure in QList<T>::at: "index out of range", file /usr/include/qt/QtCore/qlist.h, line 571
[1]    206948 abort (core dumped)  ./pkg/hippoplayer-git/usr/bin/hippoplayer</code></pre>

**Comment by emoon** [comment]
Hum.. that is odd. Can you get a callstack from the crash?

**Comment by ragouel** [comment]
Yes.
[strace.log](https://github.com/emoon/HippoPlayer/files/4792344/strace.log)

**Comment by ragouel** [comment]
Yes.
[strace.log](https://github.com/emoon/HippoPlayer/files/4792365/strace.log)

**Comment by ragouel** [comment]
This is what I used to create the binary.

<pre><code>  cd hippoplayer
  sed -i "123s|.*|const char* core_name = \"/home/crow/Git/AUR/hippoplayer-git/src/hippoplayer/t2-output/linux-gcc-debug-default/libhippo_core.so\";|" src/hippo_core_loader/hippo_core_loader.c
  sed -i "s|VGMEnd|VGMEndFmts|g" src/plugins/playback/vgm/VGMPlay/VGMPlay_AddFmts.c
  cd hippoplayer
  export QT5_INC=/usr/include/qt
  export QT5_BIN=/usr/bin
  export QT5_LIB=/usr/lib
  rustup install stable
  rustup default stable
  tundra2 -D linux-gcc-debug</code></pre>

**Comment by emoon** [comment]
This path looks a bit strange

**Comment by ragouel** [comment]
Yes, I'm using makepkg to produce an Arch package. It clones the repo and runs the build above build script.

**Comment by emoon** [comment]
the first `sed` above looks incorrect, you want the path to point to `/home/crow/Git/AUR/hippoplayer-git/src/t2-output/linux-gcc-debug-default/libhippo_core.so`

**Comment by emoon** [comment]
Also I can try to fix this today so this isn't needed.

**Comment by ragouel** [comment]
The repo is cloned inside `src/` dir, "hippoplayer" is the folder where the code is.

**Comment by emoon** [comment]
hum... the last thing seen in the `strace` log is this

```
Unable to open /home/crow/Git/AUR/hippoplayer-git/src/hippoplayer/t2-output/linux-gcc-debug-default/libhippo_core.so: /home/crow/Git/AUR/hippoplayer-git/src/hippoplayer/t2-output/linux-gcc-debug-default/libhippo_core.so: cannot open shared object file: No such file or directory) = 278
```

Can you verify that this is the correct path?

**Comment by ragouel** [comment]
I had moved the folder after installing the package. This is the proper log. 
[strace.log](https://github.com/emoon/HippoPlayer/files/4792499/strace.log)

**Comment by emoon** [comment]
```
openat(AT_FDCWD, "data/fonts/DejaVuSansMono.ttf", O_RDONLY) = -1 ENOENT (No such file or directory)
```

it seems it can't open this file. The executable needs to be executed from the root directory currently so it can load the file(s) above.

**Comment by ragouel** [comment]
ok, it now runs but there's no sound

**Comment by emoon** [comment]
hum.. can you share the file you are trying to play? (just to verify that it works on my side)

**Comment by ragouel** [comment]
Tried it with various mp3 files


<pre><code>Unable to find plugin to support /home/crow/Music/Music/Adele - Rolling In The Deep.mp3
/home/crow/Music/Music/Juno Reactor - Mona Lisa Overdrive.mp3
nsf unsupported
Unable to find plugin to support /home/crow/Music/Music/Juno Reactor - Mona Lisa Overdrive.mp3</code></pre>

**Comment by emoon** [comment]
MP3 isn't supported yet. Here are the supported formats https://github.com/emoon/HippoPlayer/issues/13

You can try this one https://api.modarchive.org/downloads.php?moduleid=33431#ambpower.mod and see if it plays

**Comment by ragouel** [comment]
Yep, that one works.

**Comment by emoon** [comment]
Great. MP3 support will be added at some point also

**Comment by ragouel** [comment]
Awesome. I added [hippoplayer](https://aur.archlinux.org/packages/hippoplayer-git/) to the [Arch User Repository](https://aur.archlinux.org/).

**Comment by emoon** [comment]
Sweet! Right now I guess the debug version is used because it's the only one really being tested. Going forward I will make sure that release version work which should reduce CPU usage quite a bit.
