### ISSUE TITLE
hippoplayer windows can't play DRO files

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [emoon/HippoPlayer#83]
Hi

I just tried hippoplayer for windows but it can't play any DRO files.
The files are in the playlist added but if you click or double click them, they don't play.

DRO files are supported by adplug and can be played by other players that use adplug (for example audacious)

. They can be made by capturing using dosbox 
https://www.dosbox.com/

Here is an example DRO file

http://www.mediafire.com/file/4sumi1v3kzdpyx4/Monster_Bash_-_main_menu.dro/file

Jessica

**Comment by emoon** [comment]
Hey Jessica,

It should be fixed in this version https://github.com/emoon/HippoPlayer/releases/download/0.1.1/hippoplayer_win_0.1.1.7z (some files were missed)

**Comment by jessicajonesunitedkingdom** [comment]
Thx
Working!
