### ISSUE TITLE
hippoplayer_win_0.1.1 player does not stop

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [emoon/HippoPlayer#84]
In hippoplayer_win_0.1.1 you can't stop playback of a file by clicking the stop button

**Comment by emoon** [comment]
Thanks for the report. I will try to fix this today

**Comment by emoon** [comment]
Fixed in https://github.com/emoon/HippoPlayer/releases/tag/0.1.2

**Comment by emoon** [comment]
Did some more fixes in https://github.com/emoon/HippoPlayer/releases/tag/0.1.3 (now delete from playlist works)
