### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ghost** [emoon/HippoPlayer#87]
Hi

I get the following error message in the black window:

QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)"
"DejaVu Sans Mono"

**Comment by emoon** [comment]
This is a known issues and will be fixed in 0.2

**Comment by emoon** [comment]
This has been fixed in 0.1.8
