### ISSUE TITLE
adplug DLL

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [emoon/HippoPlayer#90]
Hi

Is it possible (since this is not a hippoplayer question) to tell me by email how you compiled adplug source code to a DLL which is used by hippoplayer? I try to do this using visual studio.

There is a visual studio solution in adplug's github but when I try to compile, it's missing the file "version.h"

I'm learning to do this myself in order to use the DLL in a C# program. This should be possible.

**Comment by emoon** [comment]
I have the file here https://github.com/emoon/HippoPlayer/blob/master/src/plugins/playback/adplug/adplug_lib/src/version.h
I think it's generated when you run `configure` from the command line in the `adplug` source.

To compile to a dll I don't use VS studio directly but I use another buildsystem that will call the compiler directly. I also define a plugin interface as can be seen here in here

https://github.com/emoon/HippoPlayer/blob/master/src/plugins/playback/adplug/adplug_plugin.cpp#L222-L245

That my loader code uses and then calls later on.

**Comment by jessicajonesunitedkingdom** [comment]
Hi

The problem with version.h is solved!

Visual studio compiles a .LIB file (no .DLL) sucessfully now.

Do you know somebody who knows how to compile a .DLL using visual studio instead of this .LIB file?

I asked on adplug github but there is virtually NO reaction at all...
(even about a bug I found in adplug too)

Thx

**Comment by emoon** [comment]
If you want to do it all from Visual Studio you have two options:

1. Add a new project (Dynamic-Link Library (DLL) to your solution and then have this depend on the `.lib` project from adplug
2. Add a new project (Dynamic-Link Library (DLL) to your solution and "move" the files from the `.lib` project (along with it's settings, such as defines etc) over to the dll project.

**Comment by emoon** [comment]
I read a bit on the issue on adplug. I wanted to make clear I use the Visual Studio compiler on Windows but I do *not* use regular Visual Studio projects. I also have applied the fix so the files here http://www.shikadi.net/wiki/files/keenmusic-r3.zip can be played in 0.1.4 version of HippoPlayer.

**Comment by jessicajonesunitedkingdom** [comment]
thx a lot!
for being a free player, the support you give is FANTASTIC!
Your player will soon be my default player!

If you read my other question on adplug about the DLL: they say I need to add additional code to adplug to be able to compile a DLL.
I have no idea where and what code.

You know this?

I have a DLL C++ visual studio solution now that contains all the files from the LIB  project.
But what's the next step to do?

thx

**Comment by emoon** [comment]
> If you read my other question on adplug about the DLL: they say I need to add additional code to adplug to be able to compile a DLL.
I have no idea where and what code.

You don't need additional code to compile the DLL, but you will need additional code to actually use it (i.e calling the code from C#) I haven't done such myself from C# so I don't know what that involves, but I expect it should be included in the C# documentation

**Comment by jessicajonesunitedkingdom** [comment]
What I'm also wondering: how can you use visual studio compiler without using the IDE?
Is this what you mean?

If I make a DLL solution in visual studio, put all file in there, and compile: is this doing the exact same as what you do?
I have actually no idea what exactly you do to compile using visual studio without using the projects of visual studio.

**Comment by emoon** [comment]
> What I'm also wondering: how can you use visual studio compiler without using the IDE? Is this what you mean?

Visual Studio itself comes with the compiler and linker that you can run from the command line (cmd) (i.e with out the VS IDE) they are called `cl.exe` and `link.exe` so the build system I use will call those tools with the correct command line parameters.

> If I make a DLL solution in visual studio, put all file in there, and compile: is this doing the exact same as what you do? I have actually no idea what exactly you do to compile using visual studio without using the projects of visual studio.

That will produce a similar result yes. The way it works is that the project is a description of how to call `cl.exe` and `link.exe` and that is what VS will do from the IDE.

**Comment by jessicajonesunitedkingdom** [comment]
Hi

Is it possible to tell me how this last message of me is possible according to you?
I just don't understand :)

https://github.com/adplug/adplug/issues/116

I'm giving up, nobody really helps me and I have a very simple question (see that last message).

How can you compile your DLL using visual studio without using "extern"?
I just don't understand. I read tutorials and you must tell for each method the DLL exports by using "extern"
Since I don't know how adplug works internally, I don't know in what source code file and which method(s) to export using "extern"

I just need a method the DLL provides to load a file and play it using adplug.
That's all :)

**Comment by emoon** [comment]
Adplug doesn't provide a way to just open a file and play it. You need to call the functions that opens a file and decodes the samples yourself.

> How can you compile your DLL using visual studio without using "extern"?

I do use extern. See this code

https://github.com/emoon/HippoPlayer/blob/master/src/plugins/playback/adplug/adplug_plugin.cpp#L243

In my case I export one single function that returns a struct of function pointers. This is what I use later on (and this is what all plugins does)

Then later (in the main HippoPlayer) `open` will be called on a file name and then to generate samples `read_data` will be called.

**Comment by jessicajonesunitedkingdom** [comment]
i don't understand anything
so adplug'is a'library that can NOT play a file?

how can i'play samples in C#?

**Comment by jessicajonesunitedkingdom** [comment]
DAMNIT I WANT A DLL OF ADPLUG
NOBODY HELPS ME

SUCK MY FUCKONG CLIT RETARD LOSER

**Comment by emoon** [comment]
Yes. So the way it works is that you first have some code like this

https://github.com/emoon/HippoPlayer/blob/master/src/plugins/playback/adplug/adplug_plugin.cpp#L75-L88

This will open the file (`url` here is a pointer to the filename)

Then you have to have some code like this

https://github.com/emoon/HippoPlayer/blob/master/src/plugins/playback/adplug/adplug_plugin.cpp#L113-L154

In C# just must use something to play those generated samples. I don't know how to do this (as I don't use C#) but perhaps search google on C# waveout

**Comment by jessicajonesunitedkingdom** [comment]
Thank you for the explanation, I understand it now but not the code.
So I have no experience with this and I give up :(

**Comment by emoon** [comment]
Alright. I understand.

Is it ok to close this one now?

**Comment by jessicajonesunitedkingdom** [comment]
Can you explain what each line of adplug_read_data is doing?

I found this!
https://www.nuget.org/packages/adplug

If i install this, do i have a DLL of adplug then?
And how to find out what methods the DLL have?

Where is the API and examples of adplug for playing files?
I don't find anything

**Comment by jessicajonesunitedkingdom** [comment]
grrrrrrrrrrrrrr!!!!!!!!!!!
this nuget also only has a LIB, no DLL
what's wrong with those adplug guys

**Comment by emoon** [comment]
> https://www.nuget.org/packages/adplug

I look at this package and it seems to only include a lib (not dll) so it will not help you any more than the existing VS project that comes with adplug I think.

> Where is the API and examples of adplug for playing files? I don't find anything

I couldn't find any docs for it. I had to look in this code to figure out how to use it.

https://github.com/adplug/adplay-unix

> this nuget also only has a LIB, no DLL what's wrong with those adplug guys.

If you are doing to use adplug from C/C++ you don't need a DLL so I guess that is the reason.

**Comment by emoon** [comment]
Also the code for `adplug_read_data` I took from here https://github.com/adplug/adplay-unix/blob/master/src/output.cc#L61-L82

**Comment by jessicajonesunitedkingdom** [comment]
Hi

CLOSE THIS FUCKING SHIT
THIS IS THE WORST LIBRARY I HAVE EVER SEEN

IM NOT INTERESTED ANYMORE
