### ISSUE TITLE
feature request: libopenmpt

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [emoon/HippoPlayer#94]
hi

Not knowing which plugins already have been made, I think libopenmpt is very usefull

https://lib.openmpt.org/libopenmpt/

This library contains modplug library too if I'm correct

Is there a way to see for the windows version which plugins/libraries are in the player at the moment?

**Comment by emoon** [comment]
Yes, this is already supported. Here is a list of current plugins (and their formats) that is in use https://github.com/emoon/HippoPlayer/issues/13
