### ISSUE TITLE
feature request: ASIO and WASAPI

### ISSUE THREAD

**Issue by ghost** [emoon/HippoPlayer#95]
For audiophiles adding ASIO and WASAPI output plugins would be great! This is beint supported on more and more audio chips (not very expensive like back in the days)

Question: what output is used on windows now? Is it directsound?

**Comment by emoon** [comment]
WASAPI is used by default on Windows. ASIO is a bit more complex to add support for so maybe in the future.

**Comment by emoon** [comment]
This is dependant on https://github.com/dr-soft/miniaudio/issues/133 I think WASAPI is really good enough for Hippo, but I will keep a track on this issue and in case ASIO gets implemented in miniaudio it should be supported in HippoPlayer as well
